config/routes.rb
Rails.application.routes.draw do
  resources :gastos_fertilizantes
  resources :gastos_balanceados
  resources :vitaminas
  resources :desinfectantes
  resources :bacteria
  resources :fertilizantes
  resources :periodos
  resources :corridas
  resources :piscinas
  resources :balanceados
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/fertilizante.rb
class Fertilizante < ApplicationRecord

  before_validation :set_uuid, on: :create
  before_validation :transform_to_ints, on: :create

  after_find :transform_to_dec
  after_find :precio_unit

  attr_accessor :precioUnit

  def set_uuid

    self.id = SecureRandom.uuid

  end

  def precio_unit

    self.precioUnit = precio / presentacion

  end

  def transform_to_ints

    self.precio = precio * 100

  end

  def transform_to_dec

    self.precio = precio / 100

  end


end

app/controllers/fertilizantes_controller.rb
class FertilizantesController < ApplicationController
  before_action :set_fertilizante, only: [:show, :edit, :update, :destroy]

  # GET /fertilizantes
  # GET /fertilizantes.json
  def index
    @fertilizantes = Fertilizante.all
  end

  # GET /fertilizantes/1
  # GET /fertilizantes/1.json
  def show
  end

  # GET /fertilizantes/new
  def new
    @fertilizante = Fertilizante.new
  end

  # GET /fertilizantes/1/edit
  def edit
  end

  # POST /fertilizantes
  # POST /fertilizantes.json
  def create
    @fertilizante = Fertilizante.new(fertilizante_params)

    respond_to do |format|
      if @fertilizante.save
        format.html { redirect_to @fertilizante, notice: 'Fertilizante was successfully created.' }
        format.json { render :show, status: :created, location: @fertilizante }
      else
        format.html { render :new }
        format.json { render json: @fertilizante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fertilizantes/1
  # PATCH/PUT /fertilizantes/1.json
  def update
    respond_to do |format|
      if @fertilizante.update(fertilizante_params)
        format.html { redirect_to @fertilizante, notice: 'Fertilizante was successfully updated.' }
        format.json { render :show, status: :ok, location: @fertilizante }
      else
        format.html { render :edit }
        format.json { render json: @fertilizante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fertilizantes/1
  # DELETE /fertilizantes/1.json
  def destroy
    @fertilizante.destroy
    respond_to do |format|
      format.html { redirect_to fertilizantes_url, notice: 'Fertilizante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fertilizante
      @fertilizante = Fertilizante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fertilizante_params
      params.require(:fertilizante).permit(:marca, :tipo, :precio, :presentacion, :stock, :liquido)
    end
end

app/helpers/fertilizantes_helper.rb
module FertilizantesHelper
end

app/views/fertilizantes/_form.html.erb
<%= form_with(model: fertilizante, local: true) do |form| %>
  <% if fertilizante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fertilizante.errors.count, "error") %> prohibited this fertilizante from being saved:</h2>

      <ul>
      <% fertilizante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :marca %>
    <%= form.text_field :marca, id: :fertilizante_marca %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo, id: :fertilizante_tipo %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.number_field :precio, id: :fertilizante_precio %>
  </div>

  <div class="field">
    <%= form.label :presentacion %>
    <%= form.number_field :presentacion, id: :fertilizante_presentacion %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock, id: :fertilizante_stock %>
  </div>

  <div class="field">
    <%= form.label :liquido %>
    <%= form.check_box :liquido, id: :fertilizante_liquido %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fertilizantes/edit.html.erb
<h1>Editing Fertilizante</h1>

<%= render 'form', fertilizante: @fertilizante %>

<%= link_to 'Show', @fertilizante %> |
<%= link_to 'Back', fertilizantes_path %>

app/views/fertilizantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fertilizantes</h1>

<table>
  <thead>
    <tr>
      <th>Marca</th>
      <th>Tipo</th>
      <th>Precio</th>
      <th>Presentacion</th>
      <th>Stock</th>
      <th>Liquido</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fertilizantes.each do |fertilizante| %>
      <tr>
        <td><%= fertilizante.marca %></td>
        <td><%= fertilizante.tipo %></td>
        <td><%= fertilizante.precio %></td>
        <td><%= fertilizante.presentacion %></td>
        <td><%= fertilizante.stock %></td>
        <td><%= fertilizante.liquido %></td>
        <td><%= link_to 'Show', fertilizante %></td>
        <td><%= link_to 'Edit', edit_fertilizante_path(fertilizante) %></td>
        <td><%= link_to 'Destroy', fertilizante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fertilizante', new_fertilizante_path %>

app/views/fertilizantes/new.html.erb
<h1>New Fertilizante</h1>

<%= render 'form', fertilizante: @fertilizante %>

<%= link_to 'Back', fertilizantes_path %>

app/views/fertilizantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marca:</strong>
  <%= @fertilizante.marca %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @fertilizante.tipo %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @fertilizante.precio %>
</p>

<p>
  <strong>Presentacion:</strong>
  <%= @fertilizante.presentacion %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @fertilizante.stock %>
</p>

<p>
  <strong>Liquido:</strong>
  <%= @fertilizante.liquido %>
</p>

<%= link_to 'Edit', edit_fertilizante_path(@fertilizante) %> |
<%= link_to 'Back', fertilizantes_path %>