config/routes.rb
Rails.application.routes.draw do
  resources :gastos_fertilizantes
  resources :gastos_balanceados
  resources :vitaminas
  resources :desinfectantes
  resources :bacteria
  resources :fertilizantes
  resources :periodos
  resources :corridas
  resources :piscinas
  resources :balanceados
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/corrida.rb
class Corrida < ApplicationRecord

  before_validation :set_uuid, on: :create

  has_and_belongs_to_many :piscinas
  has_many :periodos

  def set_uuid

    self.id = SecureRandom.uuid

  end

end

app/controllers/corridas_controller.rb
class CorridasController < ApplicationController
  before_action :set_corrida, only: [:show, :edit, :update, :destroy]

  # GET /corridas
  # GET /corridas.json
  def index
    @corridas = Corrida.all
  end

  # GET /corridas/1
  # GET /corridas/1.json
  def show
  end

  # GET /corridas/new
  def new
    @corrida = Corrida.new
  end

  # GET /corridas/1/edit
  def edit
  end

  # POST /corridas
  # POST /corridas.json
  def create
    @corrida = Corrida.new(corrida_params)

    respond_to do |format|
      if @corrida.save
        format.html { redirect_to @corrida, notice: 'Corrida creada satisfactoriamente.' }
        format.json { render :show, status: :created, location: @corrida }
      else
        format.html { render :new }
        format.json { render json: @corrida.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /corridas/1
  # PATCH/PUT /corridas/1.json
  def update
    respond_to do |format|
      if @corrida.update(corrida_params)
        format.html { redirect_to @corrida, notice: 'Corrida actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @corrida }
      else
        format.html { render :edit }
        format.json { render json: @corrida.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /corridas/1
  # DELETE /corridas/1.json
  def destroy
    @corrida.destroy
    respond_to do |format|
      format.html { redirect_to corridas_url, notice: 'Corrida eliminada correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_corrida
      @corrida = Corrida.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def corrida_params
      params.require(:corrida).permit(:fechaInicio, :fechaFin, :estado)
    end
end

app/helpers/corridas_helper.rb
module CorridasHelper
end

app/views/corridas/_form.html.erb
<%= form_with(model: corrida, local: true) do |form| %>
  <% if corrida.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(corrida.errors.count, "error") %> prohibited this corrida from being saved:</h2>

      <ul>
      <% corrida.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fechaInicio %>
    <%= form.date_select :fechaInicio, id: :corrida_fechaInicio %>
  </div>

  <div class="field">
    <%= form.label :fechaFin %>
    <%= form.date_select :fechaFin, id: :corrida_fechaFin %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.check_box :estado, id: :corrida_estado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/corridas/edit.html.erb
<h1>Editing Corrida</h1>

<%= render 'form', corrida: @corrida %>

<%= link_to 'Show', @corrida %> |
<%= link_to 'Back', corridas_path %>

app/views/corridas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Corridas</h1>

<table>
  <thead>
    <tr>
      <th>Fechainicio</th>
      <th>Fechafin</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @corridas.each do |corrida| %>
      <tr>
        <td><%= corrida.fechaInicio %></td>
        <td><%= corrida.fechaFin %></td>
        <td><%= corrida.estado %></td>
        <td><%= link_to 'Show', corrida %></td>
        <td><%= link_to 'Edit', edit_corrida_path(corrida) %></td>
        <td><%= link_to 'Destroy', corrida, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Corrida', new_corrida_path %>

app/views/corridas/new.html.erb
<h1>New Corrida</h1>

<%= render 'form', corrida: @corrida %>

<%= link_to 'Back', corridas_path %>

app/views/corridas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fechainicio:</strong>
  <%= @corrida.fechaInicio %>
</p>

<p>
  <strong>Fechafin:</strong>
  <%= @corrida.fechaFin %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @corrida.estado %>
</p>

<%= link_to 'Edit', edit_corrida_path(@corrida) %> |
<%= link_to 'Back', corridas_path %>