config/routes.rb
Rails.application.routes.draw do
  resources :gastos_fertilizantes
  resources :gastos_balanceados
  resources :vitaminas
  resources :desinfectantes
  resources :bacteria
  resources :fertilizantes
  resources :periodos
  resources :corridas
  resources :piscinas
  resources :balanceados
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/piscina.rb
class Piscina < ApplicationRecord

  before_validation :set_uuid, on: :create

  has_and_belongs_to_many :corridas

  def set_uuid

    self.id = SecureRandom.uuid

  end

end

app/controllers/piscinas_controller.rb
class PiscinasController < ApplicationController
  before_action :set_piscina, only: [:show, :edit, :update, :destroy]

  # GET /piscinas
  # GET /piscinas.json
  def index
    @piscinas = Piscina.all
  end

  # GET /piscinas/1
  # GET /piscinas/1.json
  def show
  end

  # GET /piscinas/new
  def new
    @piscina = Piscina.new
  end

  # GET /piscinas/1/edit
  def edit
  end

  # POST /piscinas
  # POST /piscinas.json
  def create
    @piscina = Piscina.new(piscina_params)

    respond_to do |format|
      if @piscina.save
        format.html { redirect_to @piscina, notice: 'Piscina creada correctamente' }
        format.json { render :show, status: :created, location: @piscina }
      else
        format.html { render :new }
        format.json { render json: @piscina.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /piscinas/1
  # PATCH/PUT /piscinas/1.json
  def update
    respond_to do |format|
      if @piscina.update(piscina_params)
        format.html { redirect_to @piscina, notice: 'Piscina actualizada satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @piscina }
      else
        format.html { render :edit }
        format.json { render json: @piscina.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /piscinas/1
  # DELETE /piscinas/1.json
  def destroy
    @piscina.destroy
    respond_to do |format|
      format.html { redirect_to piscinas_url, notice: 'Piscina eliminada correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_piscina
      @piscina = Piscina.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def piscina_params
      params.require(:piscina).permit(:nombre, :hectareas, :estado)
    end
end

app/helpers/piscinas_helper.rb
module PiscinasHelper
end

app/views/piscinas/_form.html.erb
<%= form_with(model: piscina, local: true) do |form| %>
  <% if piscina.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(piscina.errors.count, "error") %> prohibited this piscina from being saved:</h2>

      <ul>
      <% piscina.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :piscina_nombre %>
  </div>

  <div class="field">
    <%= form.label :hectareas %>
    <%= form.number_field :hectareas, id: :piscina_hectareas %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.check_box :estado, id: :piscina_estado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/piscinas/edit.html.erb
<h1>Editing Piscina</h1>

<%= render 'form', piscina: @piscina %>

<%= link_to 'Show', @piscina %> |
<%= link_to 'Back', piscinas_path %>

app/views/piscinas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Piscinas</h1>

<div class="container-fluid">

  <% @piscinas.in_groups_of(3, false) do |group| %>

      <div class="row align-items-center">

        <% group.each do |piscina| %>

            <div class="col-sm">

              <div class="card" style="width: 20rem;">

                <div class="card-body">
                  <h4 class="card-title">
                    <%= piscina.nombre if piscina %>
                  </h4>
                  <p class="card-text">
                    <%= piscina.hectareas if piscina %> Ha.
                  </p>
                  <a>
                    <%= link_to piscina, class: 'btn btn-success' do %>
                        <%= octicon "file" %>
                    <% end %>
                  </a>
                  <a>
                    <%= link_to edit_piscina_path(piscina), class: 'btn btn-warning' do %>
                        <%= octicon "pencil" %>
                    <% end %>
                  </a>
                  <a>
                    <%= link_to piscina, method: :delete, data: {confirm: 'Estás Seguro?'}, class: 'btn btn-danger' do %>
                        <%= octicon "trashcan" %>
                    <% end %>
                  </a>
                </div>

              </div>

            </div>

        <% end %>

      </div>


  <% end %>

</div>


<br>

<%= link_to 'Añadir Piscina', new_piscina_path, class: 'btn btn-info' %>

app/views/piscinas/new.html.erb
<h1>Nueva Piscina</h1>

<%= render 'form', piscina: @piscina %>

<%= link_to 'Regresar', piscinas_path %>

app/views/piscinas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @piscina.nombre %>
</p>

<p>
  <strong>Hectareas:</strong>
  <%= @piscina.hectareas %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @piscina.estado %>
</p>

<%= link_to 'Edit', edit_piscina_path(@piscina) %> |
<%= link_to 'Back', piscinas_path %>