config/routes.rb
Rails.application.routes.draw do
  resources :gastos_fertilizantes
  resources :gastos_balanceados
  resources :vitaminas
  resources :desinfectantes
  resources :bacteria
  resources :fertilizantes
  resources :periodos
  resources :corridas
  resources :piscinas
  resources :balanceados
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/desinfectante.rb
class Desinfectante < ApplicationRecord

  before_validation :set_uuid, on: :create



  def set_uuid

    self.id = SecureRandom.uuid

  end

end

app/controllers/desinfectantes_controller.rb
class DesinfectantesController < ApplicationController
  before_action :set_desinfectante, only: [:show, :edit, :update, :destroy]

  # GET /desinfectantes
  # GET /desinfectantes.json
  def index
    @desinfectantes = Desinfectante.all
  end

  # GET /desinfectantes/1
  # GET /desinfectantes/1.json
  def show
  end

  # GET /desinfectantes/new
  def new
    @desinfectante = Desinfectante.new
  end

  # GET /desinfectantes/1/edit
  def edit
  end

  # POST /desinfectantes
  # POST /desinfectantes.json
  def create
    @desinfectante = Desinfectante.new(desinfectante_params)

    respond_to do |format|
      if @desinfectante.save
        format.html { redirect_to @desinfectante, notice: 'Desinfectante was successfully created.' }
        format.json { render :show, status: :created, location: @desinfectante }
      else
        format.html { render :new }
        format.json { render json: @desinfectante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /desinfectantes/1
  # PATCH/PUT /desinfectantes/1.json
  def update
    respond_to do |format|
      if @desinfectante.update(desinfectante_params)
        format.html { redirect_to @desinfectante, notice: 'Desinfectante was successfully updated.' }
        format.json { render :show, status: :ok, location: @desinfectante }
      else
        format.html { render :edit }
        format.json { render json: @desinfectante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /desinfectantes/1
  # DELETE /desinfectantes/1.json
  def destroy
    @desinfectante.destroy
    respond_to do |format|
      format.html { redirect_to desinfectantes_url, notice: 'Desinfectante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_desinfectante
      @desinfectante = Desinfectante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def desinfectante_params
      params.require(:desinfectante).permit(:marca, :tipo, :precio, :presentacion, :stock, :liquido)
    end
end

app/helpers/desinfectantes_helper.rb
module DesinfectantesHelper
end

app/views/desinfectantes/_form.html.erb
<%= form_with(model: desinfectante, local: true) do |form| %>
  <% if desinfectante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(desinfectante.errors.count, "error") %> prohibited this desinfectante from being saved:</h2>

      <ul>
      <% desinfectante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :marca %>
    <%= form.text_field :marca, id: :desinfectante_marca %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo, id: :desinfectante_tipo %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.number_field :precio, id: :desinfectante_precio %>
  </div>

  <div class="field">
    <%= form.label :presentacion %>
    <%= form.number_field :presentacion, id: :desinfectante_presentacion %>
  </div>

  <div class="field">
    <%= form.label :stock %>
    <%= form.number_field :stock, id: :desinfectante_stock %>
  </div>

  <div class="field">
    <%= form.label :liquido %>
    <%= form.check_box :liquido, id: :desinfectante_liquido %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/desinfectantes/edit.html.erb
<h1>Editing Desinfectante</h1>

<%= render 'form', desinfectante: @desinfectante %>

<%= link_to 'Show', @desinfectante %> |
<%= link_to 'Back', desinfectantes_path %>

app/views/desinfectantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Desinfectantes</h1>

<table>
  <thead>
    <tr>
      <th>Marca</th>
      <th>Tipo</th>
      <th>Precio</th>
      <th>Presentacion</th>
      <th>Stock</th>
      <th>Liquido</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @desinfectantes.each do |desinfectante| %>
      <tr>
        <td><%= desinfectante.marca %></td>
        <td><%= desinfectante.tipo %></td>
        <td><%= desinfectante.precio %></td>
        <td><%= desinfectante.presentacion %></td>
        <td><%= desinfectante.stock %></td>
        <td><%= desinfectante.liquido %></td>
        <td><%= link_to 'Show', desinfectante %></td>
        <td><%= link_to 'Edit', edit_desinfectante_path(desinfectante) %></td>
        <td><%= link_to 'Destroy', desinfectante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Desinfectante', new_desinfectante_path %>

app/views/desinfectantes/new.html.erb
<h1>New Desinfectante</h1>

<%= render 'form', desinfectante: @desinfectante %>

<%= link_to 'Back', desinfectantes_path %>

app/views/desinfectantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marca:</strong>
  <%= @desinfectante.marca %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @desinfectante.tipo %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @desinfectante.precio %>
</p>

<p>
  <strong>Presentacion:</strong>
  <%= @desinfectante.presentacion %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @desinfectante.stock %>
</p>

<p>
  <strong>Liquido:</strong>
  <%= @desinfectante.liquido %>
</p>

<%= link_to 'Edit', edit_desinfectante_path(@desinfectante) %> |
<%= link_to 'Back', desinfectantes_path %>